import Chakra from "./_chakra/provider";
import Font from "./_font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <Font/>
      <body>
        <Chakra>{children}</Chakra>
      </body>
    </html>
  );
}
